In [ ]:
!pip install -q "transformers==4.40.2" "peft==0.6.2" "accelerate==0.30.1" "bitsandbytes==0.43.1" "trl==0.4.7" "safetensors>=0.3.1"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.7/174.7 kB 5.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.6/302.6 kB 11.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.8/119.8 MB 13.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.4/77.4 kB 12.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.0/542.0 kB 52.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 17.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 25.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 20.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 401.2/401.2 kB 48.1 MB/s eta 0:00:00


In [ ]:
from transformers import LlavaNextProcessor, LlavaNextForConditionalGeneration
import torch
from PIL import Image
import requests

processor = LlavaNextProcessor.from_pretrained("llava-hf/llava-v1.6-mistral-7b-hf")

model = LlavaNextForConditionalGeneration.from_pretrained("llava-hf/llava-v1.6-mistral-7b-hf", torch_dtype=torch.float16, device_map='cuda', low_cpu_mem_usage=True)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


preprocessor_config.json:   0%|          | 0.00/754 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.85k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.80M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/41.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/552 [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


config.json:   0%|          | 0.00/1.28k [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/70.2k [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/380M [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

In [ ]:
image = Image.open('/content/volley.jpg')
prompt = "[INST] <image>\nWhat is shown in this image? [/INST]"

inputs = processor(prompt, image, return_tensors="pt").to("cuda:0")

# autoregressively complete prompt
output = model.generate(**inputs, max_new_tokens=100)

print(processor.decode(output[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


[INST]  
What is shown in this image? [/INST] The image shows a beach volleyball match in progress. There are three players on the court, two of whom are in the air, reaching for the ball. The player in the middle is wearing a white jersey with the number 22, while the players on the sides are wearing yellow jerseys with the numbers 13 and 12. The setting appears to be a beach volleyball tournament, as indicated by the banners and the crowd in the background. The


The image shows a beach volleyball match in progress. There are three players on the court, two of whom are in the air, reaching for the ball. The player in the middle is wearing a white jersey with the number 22, while the players on the sides are wearing yellow jerseys with the numbers 13 and 12. The setting appears to be a beach volleyball tournament, as indicated by the banners and the crowd in the background. The

In [ ]:
image = Image.open('/content/volley.jpg')
prompt = "[INST] <image>\nWhat is written in net? [/INST]"

inputs = processor(prompt, image, return_tensors="pt").to("cuda:0")

# autoregressively complete prompt
output = model.generate(**inputs, max_new_tokens=100)

print(processor.decode(output[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


[INST]  
What is written in net? [/INST] The net in the image has the words "BEACH VOLLEYBALL" written on it. 


In [ ]:
image = Image.open('/content/y7.png')
prompt = "[INST] <image>\nWhat is shown in this image? [/INST]"

inputs = processor(prompt, image, return_tensors="pt").to("cuda:0")

# autoregressively complete prompt
output = model.generate(**inputs, max_new_tokens=100)

print(processor.decode(output[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


[INST]  
What is shown in this image? [/INST] The image shows a woman standing outdoors. She has a pink top with a black collar and a black and white striped pattern on the front. Her hair is styled in a half-up, half-down fashion, and she has a neutral expression on her face. In the background, there is a blurred view of what appears to be the Eiffel Tower, suggesting that the location might be Paris. The image has a watermark that reads "Ko," which could indicate the


The image shows a woman standing outdoors. She has a pink top with a black collar and a black and white striped pattern on the front. Her hair is styled in a half-up, half-down fashion, and she has a neutral expression on her face. In the background, there is a blurred view of what appears to be the Eiffel Tower, suggesting that the location might be Paris. The image has a watermark that reads "Ko," which could indicate the

In [ ]:
image = Image.open('/content/y1.png')
prompt = "[INST] <image>\nWhat is shown in this image? [/INST]"

inputs = processor(prompt, image, return_tensors="pt").to("cuda:0")

# autoregressively complete prompt
output = model.generate(**inputs, max_new_tokens=250)

print(processor.decode(output[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


[INST]  
What is shown in this image? [/INST] The image shows a scene with three individuals in front of a large, blue door with the word "CENTRAL PRISON" written above it. The door has a series of small, round protrusions, which could be part of a security feature. There are two uniformed individuals on either side of the door, and one person is stepping out of the door, looking surprised or concerned. The setting appears to be an urban environment, and the overall tone of the image suggests a narrative that might involve themes of incarceration or escape. 


The image shows a scene with three individuals in front of a large, blue door with the word "CENTRAL PRISON" written above it. The door has a series of small, round protrusions, which could be part of a security feature. There are two uniformed individuals on either side of the door, and one person is stepping out of the door, looking surprised or concerned. The setting appears to be an urban environment, and the overall tone of the image suggests a narrative that might involve themes of incarceration or escape.

In [ ]:
image = Image.open('/content/y15.png')
prompt = "[INST] <image>\nWhat is shown in this image? [/INST]"

inputs = processor(prompt, image, return_tensors="pt").to("cuda:0")

# autoregressively complete prompt
output = model.generate(**inputs, max_new_tokens=250)

print(processor.decode(output[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


[INST]  
What is shown in this image? [/INST] The image shows a motorcycle with a large green box or crate attached to the back. The motorcycle is parked on a dirt surface, and there are several people in the background, suggesting this might be a public area or a marketplace. The license plate of the motorcycle is visible and reads "WP 799." The setting appears to be outdoors, possibly in a rural or semi-urban area. 


The image shows a motorcycle with a large green box or crate attached to the back. The motorcycle is parked on a dirt surface, and there are several people in the background, suggesting this might be a public area or a marketplace. The license plate of the motorcycle is visible and reads "WP 799." The setting appears to be outdoors, possibly in a rural or semi-urban area.

In [ ]:
image = Image.open('/content/y9.png')
prompt = "[INST] <image>\nWhat are the actors in this image? [/INST]"

inputs = processor(prompt, image, return_tensors="pt").to("cuda:0")

# autoregressively complete prompt
output = model.generate(**inputs, max_new_tokens=250)

print(processor.decode(output[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


[INST]  
What are the actors in this image? [/INST] The actors in this image are Ranveer Singh and Deepika Padukone. They are known for their roles in Bollywood films. 


In [ ]:
image = Image.open('/content/y10.png')
prompt = "[INST] <image>\nWhat are the actors in this image? [/INST]"

inputs = processor(prompt, image, return_tensors="pt").to("cuda:0")

# autoregressively complete prompt
output = model.generate(**inputs, max_new_tokens=250)

print(processor.decode(output[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


[INST]  
What are the actors in this image? [/INST] The actors in this image are Sanjay Dutt and Paresh Rawal. They are known for their roles in Indian cinema. 


In [ ]:
image = Image.open('/content/nesan-shop.jpeg')
prompt = "[INST] <image>\nWhat is this image, extract data from this image [/INST]"

inputs = processor(prompt, image, return_tensors="pt").to("cuda:0")

# autoregressively complete prompt
output = model.generate(**inputs, max_new_tokens=500)

print(processor.decode(output[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


[INST]  
What is this image, extract data from this image [/INST] The image appears to be a handwritten list of items with their corresponding prices, likely from a store or market. The list is in Tamil, and it includes various items such as "New Luxury Stores," "Navinil, Karaveddy," and "T.P. 077928396." The prices are listed in Indian Rupees (INR). Here is the data extracted from the image:

```
Item                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

What is this image, extract data from this image [/INST] The image appears to be a handwritten list of items with their corresponding prices, likely from a store or market. The list is in Tamil, and it includes various items such as "New Luxury Stores," "Navinil, Karaveddy," and "T.P. 077928396." The prices are listed in Indian Rupees (INR). Here is the data extracted from the image: